kind: Service
apiVersion: v1
metadata:
  name: Additionapp-service
spec:
  type: NodePort
  selector:
    app: Additionapp-service
  ports:
  - protocol: TCP
    targetPort: 8090
    port: 8090
    nodePort: 30809
	
---	
	
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Additionapp-deployment
  labels:
    app: Additionapp-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: Additionapp-service
  template:
    metadata:
      labels:
        app: Additionapp-service
    spec:
      containers:
      - name: Additionapp-service
        image: siva3100/Additionapp:0.$BUILD_NUMBER
        ports:
        - containerPort: 8090
		
---

kind: Service
apiVersion: v1
metadata:
  name: RESTfulExample-service
spec:
  type: NodePort
  selector:
    app: RESTfulExample-service
  ports:
  - protocol: TCP
    targetPort: 8001
    port: 8001
    nodePort: 30801

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: RESTfulExample-deployment
  labels:
    app: RESTfulExample-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: RESTfulExample-service
  template:
    metadata:
      labels:
        app: RESTfulExample-service
    spec:
      containers:
      - name: RESTfulExample-service
        image: siva3100/RESTfulExample:0.$BUILD_NUMBER
        ports:
        - containerPort: 8001